CREATE TABLE user
(
   ID int PRIMARY KEY NOT NULL,
   USERNAME varchar(32) NOT NULL,
   NAME varchar(64) NOT NULL
)
;
CREATE UNIQUE INDEX PRIMARY ON user(ID)
;
CREATE UNIQUE INDEX USERNAME ON user(USERNAME)
;
