//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.16 at 01:42:05 PM EDT 
//


package com.guru.test.ftp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.guru.test.ftp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.guru.test.ftp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FtpServiceConfig }
     * 
     */
    public FtpServiceConfig createFtpServiceConfig() {
        return new FtpServiceConfig();
    }

    /**
     * Create an instance of {@link FtpServiceConfig.FtpServer }
     * 
     */
    public FtpServiceConfig.FtpServer createFtpServiceConfigFtpServer() {
        return new FtpServiceConfig.FtpServer();
    }

    /**
     * Create an instance of {@link FtpServiceConfig.FtpServer.DataFile }
     * 
     */
    public FtpServiceConfig.FtpServer.DataFile createFtpServiceConfigFtpServerDataFile() {
        return new FtpServiceConfig.FtpServer.DataFile();
    }

}
