//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.lps.test.webservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lps.test.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckLoanStatus_QNAME = new QName("http://webservice.test.lps.com/", "checkLoanStatus");
    private final static QName _CheckLoanStatusResponse_QNAME = new QName("http://webservice.test.lps.com/", "checkLoanStatusResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lps.test.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckLoanStatus }
     * 
     */
    public CheckLoanStatus createCheckLoanStatus() {
        return new CheckLoanStatus();
    }

    /**
     * Create an instance of {@link CheckLoanStatusResponse }
     * 
     */
    public CheckLoanStatusResponse createCheckLoanStatusResponse() {
        return new CheckLoanStatusResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckLoanStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.test.lps.com/", name = "checkLoanStatus")
    public JAXBElement<CheckLoanStatus> createCheckLoanStatus(CheckLoanStatus value) {
        return new JAXBElement<CheckLoanStatus>(_CheckLoanStatus_QNAME, CheckLoanStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckLoanStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webservice.test.lps.com/", name = "checkLoanStatusResponse")
    public JAXBElement<CheckLoanStatusResponse> createCheckLoanStatusResponse(CheckLoanStatusResponse value) {
        return new JAXBElement<CheckLoanStatusResponse>(_CheckLoanStatusResponse_QNAME, CheckLoanStatusResponse.class, null, value);
    }

}
