//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.lps.test.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "TestWebservice", targetNamespace = "http://webservice.test.lps.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkLoanStatus", targetNamespace = "http://webservice.test.lps.com/", className = "com.lps.test.webservice.CheckLoanStatus")
    @ResponseWrapper(localName = "checkLoanStatusResponse", targetNamespace = "http://webservice.test.lps.com/", className = "com.lps.test.webservice.CheckLoanStatusResponse")
    public String checkLoanStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
