//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.lps.test.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "TestWebserviceImplService", targetNamespace = "http://webservice.test.lps.com/", wsdlLocation = "http://localhost:8080/services/TestWebservice?wsdl")
public class TestWebserviceImplService
    extends Service
{

    private final static URL TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lps.test.webservice.TestWebserviceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lps.test.webservice.TestWebserviceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8888/services/TestWebservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/services/TestWebservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public TestWebserviceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebserviceImplService() {
        super(TESTWEBSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.test.lps.com/", "TestWebserviceImplService"));
    }

    /**
     * 
     * @return
     *     returns TestWebservice
     */
    @WebEndpoint(name = "TestWebserviceImplPort")
    public TestWebservice getTestWebserviceImplPort() {
        return super.getPort(new QName("http://webservice.test.lps.com/", "TestWebserviceImplPort"), TestWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebservice
     */
    @WebEndpoint(name = "TestWebserviceImplPort")
    public TestWebservice getTestWebserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.test.lps.com/", "TestWebserviceImplPort"), TestWebservice.class, features);
    }

}
